#!/bin/bash
# One-time setup: fetch Firebase config from Secret Manager into frontend/.env.local
# Run this before first `./run.sh` or `npm run dev` if you see a blank white page.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# Hardcoded for this repo (matches .firebaserc and deploy scripts)
PROJECT_ID="data-integrity-monitor"

if [ -z "$PROJECT_ID" ]; then
  echo "Error: Could not determine GCP project. Set GCP_PROJECT_ID or run: gcloud config set project YOUR_PROJECT"
  exit 1
fi

echo "Fetching Firebase config from Secret Manager (project: $PROJECT_ID)..."

VITE_FIREBASE_API_KEY=$(gcloud secrets versions access latest --secret="FIREBASE_API_KEY" --project="$PROJECT_ID" 2>/dev/null || true)
VITE_FIREBASE_AUTH_DOMAIN=$(gcloud secrets versions access latest --secret="FIREBASE_AUTH_DOMAIN" --project="$PROJECT_ID" 2>/dev/null || true)
VITE_FIREBASE_PROJECT_ID=$(gcloud secrets versions access latest --secret="FIREBASE_PROJECT_ID" --project="$PROJECT_ID" 2>/dev/null || true)
VITE_FIREBASE_STORAGE_BUCKET=$(gcloud secrets versions access latest --secret="FIREBASE_STORAGE_BUCKET" --project="$PROJECT_ID" 2>/dev/null || true)
VITE_FIREBASE_MESSAGING_SENDER_ID=$(gcloud secrets versions access latest --secret="FIREBASE_MESSAGING_SENDER_ID" --project="$PROJECT_ID" 2>/dev/null || true)
VITE_FIREBASE_APP_ID=$(gcloud secrets versions access latest --secret="FIREBASE_APP_ID" --project="$PROJECT_ID" 2>/dev/null || true)

if [ -z "$VITE_FIREBASE_API_KEY" ] || [ -z "$VITE_FIREBASE_PROJECT_ID" ]; then
  echo ""
  echo "Error: Could not fetch Firebase secrets. You may need:"
  echo "  1. gcloud auth login"
  echo "  2. Access to project $PROJECT_ID"
  echo "  3. Or ask the project owner for frontend/.env.local values"
  echo ""
  echo "Required vars: VITE_FIREBASE_API_KEY, VITE_FIREBASE_AUTH_DOMAIN, VITE_FIREBASE_PROJECT_ID,"
  echo "  VITE_FIREBASE_STORAGE_BUCKET, VITE_FIREBASE_MESSAGING_SENDER_ID, VITE_FIREBASE_APP_ID"
  exit 1
fi

cat > .env.local << EOF
# Auto-generated by setup-local-env.sh - do not commit
VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
VITE_API_BASE=http://localhost:8000
EOF

echo "Created frontend/.env.local"
echo "Restart the frontend (or run ./run.sh again) for changes to take effect."
